# This is a TOML document

title = "Configuration of Message Switch"

logfile = "switch.log"

[server]
host = "0.0.0.0"
port = 10101
node_id = 2
mode = "normal"

[auth]
access_code = "hello_world"
admin_code = "foobar2000"
