# This is a TOML document

title = "Configuration of Message Switch client"

logfile = "switch_client.log"

[server]
host = "0.0.0.0"
port = 10101

[client]
endpoint_id = 2
role = "normal"
access_code = "hello_world"
